version: "3.8"

services:
  mysqldb:
    container_name: mysql-container
    hostname: localhost
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_HOST: "0.0.0.0"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "admin"
    ports:
      - 3306:3306
