export const cards = [
  {
    id: 1,
    title: "AI Artists",
    desc: "Add talent to AI",
    img: "https://images.pexels.com/photos/7532110/pexels-photo-7532110.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 2,
    title: "Logo Design",
    desc: "Build yor brand",
    img: "https://images.pexels.com/photos/11295165/pexels-photo-11295165.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 3,
    title: "WordPress",
    desc: "Customize your site",
    img: "https://images.pexels.com/photos/4371669/pexels-photo-4371669.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 4,
    title: "Voice Over",
    desc: "Share your message",
    img: "https://images.pexels.com/photos/7608079/pexels-photo-7608079.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 5,
    title: "Video Explainer",
    desc: "Engage your audience",
    img: "https://images.pexels.com/photos/13388047/pexels-photo-13388047.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 6,
    title: "Social Media",
    desc: "Reach more customers",
    img: "https://images.pexels.com/photos/11378899/pexels-photo-11378899.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 7,
    title: "SEO",
    desc: "Unlock growth online",
    img: "https://images.pexels.com/photos/4820241/pexels-photo-4820241.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 8,
    title: "Illustration",
    desc: "Color you dreams",
    img: "https://images.pexels.com/photos/15032623/pexels-photo-15032623.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
];

export const projects = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/1462935/pexels-photo-1462935.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Web and Mobile Design",
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Logo Design",
    username: "Morton Green",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Animated GIFs",
    username: "Emmett Potter",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Packaging Design",
    username: "Freddie Johnston",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Social Media Design",
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Illustration",
    username: "Dalton Hudson",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Book Design",
    username: "Hannah Dougherty",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Digital Marketing",
    username: "Ward Brewer",
  },
];

export const gigs = [
  {
    id: 1,
    img: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4755105U6",
    pp: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4755105U6",
    desc: "Expert em produção audiovisual, análise fílmica e avaliação educacional. Professor de Sistemas de Mídias Digitais na UFC, coordenando o LABVIS.",
    longerdesc:
      "Psicólogo graduado pela UFBA, com mestrado e doutorado em Teorias e Crítica da Literatura e da Cultura pela UFBA. Ex-professor de Cinema e Audiovisual na UFRB, coordenou o curso entre 2010-2013 e 2017-2018. Expert em produção audiovisual, análise fílmica e avaliação educacional. Atualmente, é professor adjunto de Sistemas de Mídias Digitais na UFC, coordenando o LABVIS.",
    proj: "Concepção de um Simulador para Treinamento Médico utilizando Realidade Virtual.",
    projautor: "Liliane dos Santos Machado",
    category: "Audiovisual",
    area: "Animação",
    modalidade: "Monografia",
    username: "Adriano Anunciação Oliveira",
    status: "Disponivel",
    proj2:
      "Criação de um software de Treinamento Médico utilizando Realidade Virtual.",
    projautor2: "Igor dos Santos Machado",
    proj3:
      "Matrix e Cidade dos Sonhos: Representações da Irrealidade da Ficção Contemporânea.",
    projautor3: "Décio Torres Cruz",
  },
  {
    id: 2,
    img: "https://si3.ufc.br/sigaa/verFoto?idFoto=1421611&key=a37b4ee0c64e17b3478d86d28c7b4e7f",
    pp: "https://si3.ufc.br/sigaa/verFoto?idFoto=1421611&key=a37b4ee0c64e17b3478d86d28c7b4e7f",
    desc: "Pesquisador e professor na UFC. Especialista em Desenvolvimento de Jogos, Gamificação e Interatividade. Atualmente, pesquisa experiência do usuário.",
    longerdesc:
      "Pesquisador e professor na UFC, bacharel em Ciência da Computação (UFPB), mestre e doutor em Informática. Especialista em Desenvolvimento de Jogos, Gamificação e Interatividade. Atualmente, pesquisa experiência do usuário.",
    category: "Sistemas",
    area: "Realidade Virtual",
    modalidade: "Monografia",
    username: "Alysson Diniz dos Santos",
    status: "Disponivel",
    proj: "Concepção de um Simulador para Treinamento Médico utilizando Realidade Virtual.",
    projautor: "Allan dos Santos Machado",
    proj2:
      "Criação de um software de Treinamento Médico utilizando Realidade Virtual.",
    projautor2: "Igor dos Santos Machado",
    proj3:
      "Matrix e Cidade dos Sonhos: Representações da Irrealidade da Ficção Contemporânea.",
    projautor3: "Décio Torres Cruz",
  },
  {
    id: 3,
    img: "https://lh3.googleusercontent.com/a-/ALV-UjV8P6qOVwaF-gqVZ6h11GEDP5MCdrxHN2dRSrg1I63rkj8q=s272-p-k-rw-no",
    pp: "https://lh3.googleusercontent.com/a-/ALV-UjV8P6qOVwaF-gqVZ6h11GEDP5MCdrxHN2dRSrg1I63rkj8q=s272-p-k-rw-no",
    desc: "Doutor em Ciência da Computação. Pesquisa Realidade Virtual, Entretenimento Digital, Informática na Educação, Computação Física e Direção de Arte para Multimídia.",
    longerdesc:
      "Doutor em Ciência da Computação pela UFC, é professor associado no curso de Sistemas e Mídias Digitais. Com experiência em faculdades e mercado, pesquisa Realidade Virtual, Entretenimento Digital, Informática na Educação, Computação Física e Direção de Arte para Multimídia.",
    category: "Sistemas",
    area: "Realidade Virtual",
    modalidade: "Monografia",
    username: "Antônio José Melo Leite Júnior",
    status: "Indisponivel",
    proj: "Concepção de um Simulador para Treinamento Médico utilizando Realidade Virtual.",
    projautor: "Léticia dos Santos Machado",
    proj2:
      "Criação de um software de Treinamento Médico utilizando Realidade Virtual.",
    projautor2: "Igor dos Santos Machado",
    proj3:
      "Matrix e Cidade dos Sonhos: Representações da Irrealidade da Ficção Contemporânea.",
    projautor3: "Décio Torres Cruz",
  },
  {
    id: 4,
    img: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4138083Z7",
    pp: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4138083Z7",
    desc: "Experiência em Design Gráfico, destacando-se em Design de Tipos, Caligrafia, Comunicação Visual e Design de Interfaces.",
    longerdesc:
      "Graduado em Publicidade e Propaganda, mestre em TICs em Educação e doutor em Design. Professor de Sistemas e Mídias Digitais na UFC, com experiência em Design Gráfico, destacando-se em Design de Tipos, Caligrafia, Comunicação Visual e Design de Interfaces.",
    category: "Design",
    area: "Design Gráfico",
    modalidade: "Artigo",
    username: "Carlos Eduardo Brito Novais",
    status: "Disponivel",
    proj: "Concepção de um Simulador para Treinamento Médico utilizando Realidade Virtual.",
    projautor: "Laisa dos Santos Machado",
    proj2:
      "Criação de um software de Treinamento Médico utilizando Realidade Virtual.",
    projautor2: "Ana dos Santos Machado",
    proj3:
      "Matrix e Cidade dos Sonhos: Representações da Irrealidade da Ficção Contemporânea.",
    projautor3: "Paula Torres Cruz",
  },
  {
    id: 5,
    img: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4214264D2",
    pp: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4214264D2",
    desc: "Experiência na área de Ciência da Computação, com ênfase em Engenharia de Software e Design de Som.",
    category: "Audiovisual",
    area: "Som",
    modalidade: "Relatório Técnico",
    username: "Carlos Diego Andrade de Almeida",
    status: "Disponivel",
    proj: "Concepção de um Simulador para Treinamento Médico utilizando Realidade Virtual.",
    projautor: "Exemplo dos Santos Machado",
    proj2:
      "Criação de um software de Treinamento Médico utilizando Realidade Virtual.",
    projautor2: "Daniel dos Santos Machado",
    proj3:
      "Matrix e Cidade dos Sonhos: Representações da Irrealidade da Ficção Contemporânea.",
    projautor3: "Pedro Torres Cruz",
  },
  {
    id: 6,
    img: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4731418Y5",
    pp: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4731418Y5",
    desc: "Experiência em Tecnologia Educacional, Instructional Design, formação de professores, educomunicação, design de interação e ambientes virtuais de aprendizagem.",
    category: "Design",
    modalidade: "Relatório Técnico",
    area: "Educação",
    username: "Cátia Luzia Oliveira da Silva ",
    status: "Indisponivel",
    proj: "Concepção de um Simulador para Treinamento Médico utilizando Realidade Virtual.",
    projautor: "Arthur dos Santos Machado",
    proj2:
      "Criação de um software de Treinamento Médico utilizando Realidade Virtual.",
    projautor2: "José dos Santos Machado",
    proj3:
      "Matrix e Cidade dos Sonhos: Representações da Irrealidade da Ficção Contemporânea.",
    projautor3: "Thiago Torres Cruz",
  },
  {
    id: 7,
    img: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4592620A8",
    pp: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4592620A8",
    desc: "Especialista sistemas embarcados, computação física, automação e controle, e redes de sensores sem fio.",
    longerdesc: "rtgytrgrt",
    category: "Sistemas",
    modalidade: "Relatório Técnico",
    username: "Clemilson Costa dos Santos",
    area: "Realidade Virtual",
    status: "Disponivel",
    proj: "Concepção de um Simulador para Treinamento Médico utilizando Realidade Virtual.",
    projautor: "Larissa dos Santos Machado",
    proj2:
      "Criação de um software de Treinamento Médico utilizando Realidade Virtual.",
    projautor2: "Laura  dos Santos Machado",
    proj3:
      "Matrix e Cidade dos Sonhos: Representações da Irrealidade da Ficção Contemporânea.",
    projautor3: "Júlia Torres Cruz",
  },
  {
    id: 8,
    img: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4231074D3",
    pp: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4231074D3",
    desc: "Focada em design e avaliação da UX e da experiência do jogador com ênfase na eudaimonia, engajamento do usuário, motivação e bem-estar.",
    longerdesc:
      "Ticianne Darin é professora na UFC, orientadora em Ciência da Computação, com graduação e doutorado pela mesma instituição. Desde 2007, participa de projetos de pesquisa em UX e Engenharia de Software. Recebeu prêmios em eventos científicos, coordenou o Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais (IHC) e integra a Comissão Especial de IHC da SBC. Pesquisadora afiliada ao GREat, coordena a Célula de Design e Multimídia, contribuindo em diversas publicações e eventos internacionais na área.",
    category: "Design",
    area: "Educação",
    modalidade: "Artigo",
    username: "Ticianne de Gois Ribeiro Darin",
    status: "Disponivel",
    proj: "Concepção de um Simulador para Treinamento Médico utilizando Realidade Virtual.",
    projautor: "Thainara dos Santos Machado",
    proj2:
      "Criação de um software de Treinamento Médico utilizando Realidade Virtual.",
    projautor2: "Maria dos Santos Machado",
    proj3:
      "Matrix e Cidade dos Sonhos: Representações da Irrealidade da Ficção Contemporânea.",
    projautor3: "Yuri Torres Cruz",
  },

  {
    id: 9,
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom art using midjourney generator",
    longerdesc: "rgfrgtrg",
    category: "Jogos",
    area: "UX",
    modalidade: "Artigo",
    username: "Wilton Hunt",
    status: "Disponivel",
    proj: "Concepção de um Simulador para Treinamento Médico utilizando Realidade Virtual.",
    projautor: "Isabele dos Santos Machado",
    proj2:
      "Criação de um software de Treinamento Médico utilizando Realidade Virtual.",
    projautor2: "Igor dos Santos Machado",
    proj3:
      "Matrix e Cidade dos Sonhos: Representações da Irrealidade da Ficção Contemporânea.",
    projautor3: "Décio Torres Cruz",
  },
];
